/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  content: ['./src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      boxShadow: {
        textShadowParagraph: '0px 2px 6px 0px #0000008c',
      },
      fontFamily: {
        spoqaHanSans: ['SpoqaHanSans'],
      },
      fontSize: {
        bigTitleMobile: [
          '1.875rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '120%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        bigTitleDesktop: [
          '3.75rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '120%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        descriptionBoldMobile: [
          '0.9375rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '130%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        descriptionMobile: [
          '0.8125rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Regular',
            lineHeight: '135%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        textXSmall: [
          '0.75rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Regular',
            lineHeight: '150%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 18,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        textSmall: [
          '0.875rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Regular',
            lineHeight: '150%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 21,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        textNormal: [
          '1rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Regular',
            lineHeight: '150%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 24,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        textLarge: [
          '1.125rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Regular',
            lineHeight: '150%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 27,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        textXLarge: [
          '1.25rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Regular',
            lineHeight: '150%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 30,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        textXSmallBold: [
          '0.75rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '150%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 18,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        textSmallBold: [
          '0.875rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '150%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 21,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        textNormalBold: [
          '1rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '150%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 24,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        textLargeBold: [
          '1.125rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '150%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 27,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        textXLargeBold: [
          '1.25rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '150%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 30,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        titleXSmall: [
          '1.375rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '120%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        titleSmall: [
          '1.5rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '120%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        titleNormal: [
          '1.75rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '120%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        titleLarge: [
          '2.125rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '120%',
            letterSpacing: '0em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        titleXLarge: [
          '3rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '120%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
        title2XLarge: [
          '3.75rem',
          {
            fontFamily: 'SpoqaHanSans',
            fontWeight: 'Bold',
            lineHeight: '120%',
            letterSpacing: '-0.0005em',
            paragraphSpacing: 0,
            paragraphIndent: '0rem',
            textCase: 'none',
            textDecoration: 'none',
          },
        ],
      },
      colors: {
        red100: '#faced0',
        red200: '#f59da1',
        red300: '#ef6b72',
        red400: '#ea3a43',
        red500: '#e50914',
        red600: '#b70710',
        red700: '#89050c',
        red800: '#5c0408',
        red900: '#2e0204',
        blue100: '#cce3fb',
        blue200: '#99c6f7',
        blue300: '#66aaf3',
        blue400: '#338def',
        blue500: '#0071eb',
        blue600: '#005abc',
        blue700: '#00448d',
        blue800: '#002d5e',
        blue900: '#00172f',
        green100: '#d5f8e3',
        green200: '#acf2c8',
        green300: '#82ebac',
        green400: '#58e590',
        green500: '#2ede75',
        green600: '#25b25d',
        green700: '#1c8546',
        green800: '#13592f',
        green900: '#092c17',
        gray100: '#e3e3e3',
        gray200: '#c8c8c8',
        gray300: '#acacac',
        gray400: '#919191',
        gray500: '#757575',
        gray600: '#5e5e5e',
        gray700: '#464646',
        gray800: '#2f2f2f',
        gray900: '#171717',
        gradients100: 'linear-gradient(180deg, #000000 0%, #00000000 100%)',
        gradientsWhite: '#ffffff',
        gradientsBlack: '#010101',
      },
    },
  },
}
