/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  content: ['./src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        pretendard: ['Pretendard'],
      },
      fontSize: {
        headingMedium: [
          '1rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'Bold',
            lineHeight: '140%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        headingLarge: [
          '1.333rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'Bold',
            lineHeight: '140%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        headingXl: [
          '1.776875rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'Bold',
            lineHeight: '140%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        headingXxl: [
          '2.3685625rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'Bold',
            lineHeight: '140%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        headingXxxl: [
          '3.1573125rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'Bold',
            lineHeight: '140%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        labelSmall: [
          '0.7501875rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'SemiBold',
            lineHeight: '150%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        labelMedium: [
          '1rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'SemiBold',
            lineHeight: '150%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        labelLarge: [
          '1.333rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'SemiBold',
            lineHeight: '150%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        labelXl: [
          '1.776875rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'SemiBold',
            lineHeight: '150%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        labelXxl: [
          '2.3685625rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'SemiBold',
            lineHeight: '150%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        paragraphSmall: [
          '0.7501875rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'Regular',
            lineHeight: '160%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        paragraphMedium: [
          '1rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'Regular',
            lineHeight: '160%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        paragraphLarge: [
          '1.333rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'Regular',
            lineHeight: '160%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
        paragraphXl: [
          '1.776875rem',
          {
            fontFamily: 'Pretendard',
            fontWeight: 'Regular',
            lineHeight: '160%',
            letterSpacing: 'NaNem',
            paragraphSpacing: 'none',
            textDecoration: 'none',
            textCase: 'none',
          },
        ],
      },
      boxShadow: {
        aboveHigh: '0px -16px 48px 0px #0000004d',
        aboveMedium: '0px -8px 36px 0px #00000033',
        aboveLow: '0px -4px 24px 0px #0000001a',
        belowHigh: '0px 16px 48px 0px #0000004d',
        belowMedium: '0px 8px 36px 0px #00000033',
        belowLow: '0px 4px 24px 0px #0000001a',
      },
      colors: {
        colorsWhite: '#ffffff',
        colorsPrimary: '#000000',
        colorsSecondary: '#ffffff',
        colorsTertiary: '#f5f5f5',
        colorsBlack: '#000000',
        colorsGray100: '#e1e1e1',
        colorsGray200: '#c4c4c4',
        colorsGray300: '#a6a6a6',
        colorsGray400: '#898989',
        colorsGray500: '#6b6b6b',
        colorsGray600: '#565656',
        colorsGray700: '#404040',
        colorsGray800: '#2b2b2b',
        colorsGray900: '#151515',
        colorsRed100: '#ffcccc',
        colorsRed200: '#ff9999',
        colorsRed300: '#ff6666',
        colorsRed400: '#ff3333',
        colorsRed500: '#ff0000',
        colorsRed600: '#cc0000',
        colorsRed700: '#990000',
        colorsRed800: '#660000',
        colorsRed900: '#330000',
        colorsYellow100: '#fff4cc',
        colorsYellow200: '#ffe999',
        colorsYellow300: '#ffdd66',
        colorsYellow400: '#ffd233',
        colorsYellow500: '#ffc700',
        colorsYellow600: '#cc9f00',
        colorsYellow700: '#997700',
        colorsYellow800: '#665000',
        colorsYellow900: '#332800',
        colorsBlue100: '#cce3ff',
        colorsBlue200: '#99c8ff',
        colorsBlue300: '#66acff',
        colorsBlue400: '#3391ff',
        colorsBlue500: '#0075ff',
        colorsBlue600: '#005ecc',
        colorsBlue700: '#004699',
        colorsBlue800: '#002f66',
        colorsBlue900: '#001733',
        colorsGreen100: '#d7f8cc',
        colorsGreen200: '#b0f199',
        colorsGreen300: '#88eb66',
        colorsGreen400: '#61e433',
        colorsGreen500: '#39dd00',
        colorsGreen600: '#2eb100',
        colorsGreen700: '#228500',
        colorsGreen800: '#175800',
        colorsGreen900: '#0b2c00',
        colorsInfoAccent: '#0075ff',
        colorsInfoNegative: '#ff0000',
        colorsInfoWarning: '#ffc700',
        colorsInfoPositive: '#39dd00',
        colorsInfoPositiveTransparent: '#39dd001a',
        colorsInfoNegativeTransparent: '#ff00001a',
        colorsContentsContentPrimary: '#000000',
        colorsContentsContentSecondary: '#6b6b6b',
        colorsContentsContentTertiary: '#a6a6a6',
        colorsBorderBorderTransparent: '#8989894d',
        colorsBorderBorderOpaque: '#898989',
        colorsPink100: '#fff2f5',
        colorsPink200: '#ffe6ea',
        colorsPink300: '#ffd9e0',
        colorsPink400: '#ffcdd5',
        colorsPink500: '#ffc0cb',
        colorsPink600: '#cc9aa2',
        colorsPink700: '#99737a',
        colorsPink800: '#664d51',
        colorsPink900: '#332629',
      },
    },
  },
}
